######################################################################
# Automatically generated by qmake (2.00a) Fre Mai 5 19:37:57 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h settings.h
FORMS += mainwindow.ui settings.ui
SOURCES += main.cpp
