######################################################################
# Automatically generated by qmake (2.00a) Fre Mai 5 19:29:22 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += mainwindow.ui settings.ui
SOURCES += main.cpp
